server:
  port: 8080 #服务注册中心端口号
eureka:
  instance:
    hostname: eureka.server.com
    prefer-ip-address: false
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8081/eureka/
spring:
  application:
    name: EUREKA-SERVER